"use client";

import { useState } from "react";
import { PageWidthWrapper } from "@/ui/layout/page-width-wrapper";
import SettingsChildrenLayout from "@/ui/workspaces/SettingsChildrentLayout";

type UploadStatus =
  | { state: "idle" }
  | { state: "uploading" }
  | { state: "success"; rowsImported: number }
  | { state: "error"; message: string };

function FileUploadCard({
  title,
  description,
  endpoint,
  buttonLabel,
  footnote,
}: {
  title: string;
  description: string;
  endpoint: string;
  buttonLabel: string;
  footnote: string;
}) {
  const [file, setFile] = useState<File | null>(null);
  const [status, setStatus] = useState<UploadStatus>({ state: "idle" });

  async function handleImport() {
    if (!file) return;
    setStatus({ state: "uploading" });

    const form = new FormData();
    form.append("file", file);

    try {
      const res = await fetch(endpoint, { method: "POST", body: form });
      const data = await res.json();

      if (!res.ok || !data.success) {
        setStatus({ state: "error", message: data.error ?? "Import failed" });
        return;
      }

      setStatus({ state: "success", rowsImported: data.rowsImported });
    } catch (err) {
      setStatus({
        state: "error",
        message: err instanceof Error ? err.message : "Import failed",
      });
    }
  }

  return (
    <div className="rounded-2xl p-4 py-5 px-6 bg-white">
      <div className="w-full space-y-5">
        <div>
          <h2 className="font-display text-[15px] font-medium text-neutral-500">
            {title}
          </h2>
          <p className="mt-0.5 font-display text-[13.5px] text-neutral-500">
            {description}
          </p>
        </div>

        <label className="flex h-11 cursor-pointer items-center justify-between rounded-lg border border-neutral-200 bg-neutral-50 px-2 pl-4 hover:bg-neutral-100 transition">
          <span className="truncate font-display text-[13.5px] text-neutral-400">
            {file ? file.name : "No file selected"}
          </span>
          <span className="rounded-md bg-neutral-200/70 px-4 py-1.5 text-[13.5px] font-medium text-neutral-600">
            Choose file
          </span>
          <input
            type="file"
            accept=".zip"
            className="hidden"
            onChange={(e) => setFile(e.target.files?.[0] ?? null)}
          />
        </label>

        <button
          type="button"
          disabled={!file || status.state === "uploading"}
          onClick={handleImport}
          className="flex h-11 w-full items-center justify-center rounded-lg bg-neutral-900 font-display text-sm font-medium text-white transition hover:bg-black disabled:cursor-not-allowed disabled:opacity-50"
        >
          {status.state === "uploading" ? "Importing…" : buttonLabel}
        </button>

        {status.state === "success" && (
          <p className="font-display text-xs text-green-600">
            Imported {status.rowsImported.toLocaleString()} rows successfully.
          </p>
        )}
        {status.state === "error" && (
          <p className="font-display text-xs text-red-600">
            {status.message}
          </p>
        )}

        <p className="font-display text-xs text-neutral-400">{footnote}</p>
      </div>
    </div>
  );
}

export default function Import({ workspaceId }: { workspaceId: string }) {
  return (
    <PageWidthWrapper>
      <SettingsChildrenLayout
        title="Import"
        description="Bring historical data into Convrs."
      >
        <div className="space-y-5">
          <FileUploadCard
            title="Import from Plausible"
            description="Export your data from Plausible and upload the ZIP file below."
            endpoint={`/api/workspaces/${workspaceId}/import/plausible`}
            buttonLabel="Import data"
            footnote="Only ZIP exports generated by Plausible are supported. Custom events and goals will need to be reconfigured in Convrs after import."
          />

          <FileUploadCard
            title="Import from another Convrs workspace"
            description="Upload a Convrs export ZIP (from the Export page) to bring that workspace's history into this one."
            endpoint={`/api/workspaces/${workspaceId}/import/convrs`}
            buttonLabel="Import data"
            footnote="Uses the raw_events.csv file inside the export for a lossless import — real sessions, bounce rate, and durations carry over exactly."
          />
        </div>
      </SettingsChildrenLayout>
    </PageWidthWrapper>
  );
}