"use client";

import { useState } from "react";
import { PageWidthWrapper } from "@/ui/layout/page-width-wrapper";
import SettingsChildrenLayout from "@/ui/workspaces/SettingsChildrentLayout";
import useWorkspace from "@/lib/swr/use-workspace";
import { Button } from "@repo/ui";

type UploadStatus =
  | { state: "idle" }
  | { state: "uploading" }
  | { state: "success"; rowsImported: number }
  | { state: "error"; message: string };

function FileUploadCard({
  title,
  description,
  endpoint,
  buttonLabel,
  footnote,
}: {
  title: string;
  description: string;
  endpoint: string;
  buttonLabel: string;
  footnote: string;
}) {
  const [file, setFile] = useState<File | null>(null);
  const [status, setStatus] = useState<UploadStatus>({ state: "idle" });

  async function handleImport() {
    if (!file) return;
    setStatus({ state: "uploading" });

    const form = new FormData();
    form.append("file", file);

    try {
      const res = await fetch(endpoint, { method: "POST", body: form });
      const data = await res.json();

      if (!res.ok || !data.success) {
        setStatus({ state: "error", message: data.error ?? "Import failed" });
        return;
      }

      setStatus({ state: "success", rowsImported: data.rowsImported });
    } catch (err) {
      setStatus({
        state: "error",
        message: err instanceof Error ? err.message : "Import failed",
      });
    }
  }

  return (
    <div className="rounded-2xl  bg-bg-card p-4 sm:p-4">
      <div className="w-full space-y-3">
        <h1 className="font-medium font-display text-sm text-content-subtle">1. Export your data from Plausible</h1>
        <h1 className="font-medium font-display text-sm text-content-subtle">2. Upload the zip file below</h1>

        <label className="flex h-11 cursor-pointer items-center justify-between gap-3 rounded-lg border border-border-subtle bg-bg-subtle px-2 pl-4 transition hover:bg-bg-emphasis">
          <span className="flex-1 truncate font-display text-[13.5px] text-content-subtle">
            {file ? file.name : "No file selected"}
          </span>

          <span className="shrink-0 rounded-md bg-bg-emphasis px-4 py-1.5 font-display text-[13.5px] font-medium text-content-default">
            Choose file
          </span>

          <input
            type="file"
            accept=".zip"
            className="hidden"
            onChange={(e) => setFile(e.target.files?.[0] ?? null)}
          />
        </label>

        <Button
          type="button"
          variant={"settings"}
          disabled={!file || status.state === "uploading"}
          onClick={handleImport}
          text={status.state === "uploading" ? "Importing…" : buttonLabel}
          className="rounded-xl font-display "
        />

        {status.state === "success" && (
          <p className="font-display text-xs text-green-600">
            Imported {status.rowsImported.toLocaleString()} rows successfully.
          </p>
        )}

        {status.state === "error" && (
          <p className="font-display text-xs text-red-600">
            {status.message}
          </p>
        )}

        <p className="font-display text-xs text-content-subtle">
          {footnote}
        </p>
      </div>
    </div>
  );
}

export default function Import() {
  const { id: workspaceId } = useWorkspace()
  return (
    <PageWidthWrapper>
      <SettingsChildrenLayout
        title="Import"
        description="Bring historical data into Convrs."
      >
        <div className="space-y-5">
          <FileUploadCard
            title="Import from Plausible"
            description="Export your data from Plausible and upload the ZIP file below."
            endpoint={`/api/workspaces/${workspaceId}/import/plausible`}
            buttonLabel="Import data"
            footnote="Only ZIP exports generated by Plausible are supported. Custom events and goals will need to be reconfigured in Convrs after import."
          />

          {/* <FileUploadCard
            title="Import from another Convrs workspace"
            description="Upload a Convrs export ZIP (from the Export page) to bring that workspace's history into this one."
            endpoint={`/api/workspaces/${workspaceId}/import/convrs`}
            buttonLabel="Import data"
            footnote="Uses the raw_events.csv file inside the export for a lossless import — real sessions, bounce rate, and durations carry over exactly."
          /> */}
        </div>
      </SettingsChildrenLayout>
    </PageWidthWrapper>
  );
}