import { confirmTwoFactorAuthAction } from "@/lib/actions/auth/confirm-two-factor-auth";
import { QRCode } from "@/ui/shared/qr-code";
import { Button, CopyButton, Modal } from "@repo/ui";
import { cn } from "@repo/utils";
import { OTPInput } from "input-otp";
import { useAction } from "next-safe-action/hooks";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

interface EnableTwoFactorAuthModalProps {
  showModal: boolean;
  setShowModal: (show: boolean) => void;
  onSuccess?: () => void;
  secret: string;
  qrCodeUrl: string;
}

const EnableTwoFactorAuthModal = ({
  showModal,
  setShowModal,
  onSuccess,
  secret,
  qrCodeUrl,
}: EnableTwoFactorAuthModalProps) => {
  const [token, setToken] = useState("");
  const [touched, setTouched] = useState(false);
  const [error, setError] = useState<string | undefined>(undefined);

  useEffect(() => {
    if (showModal) {
      setToken("");
      setTouched(false);
      setError(undefined);
    }
  }, [showModal]);

  const { executeAsync, isPending } = useAction(confirmTwoFactorAuthAction, {
    onSuccess: () => {
      toast.success("Two-factor authentication enabled successfully!");
      setShowModal(false);
      onSuccess?.();
    },
    onError: (error) => {
      setError("Failed to enable two-factor authentication. Please try again.");
    },
  });

  const confirmTwoFactorAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setTouched(true);
    setError(undefined);

    await executeAsync({
      token,
    });
  };

  return (
    <Modal
      showModal={showModal}
      setShowModal={setShowModal}
      className="px-4 md:px-0 py-3 md:py-1.5 max-h-[90vh] md:max-h-[95dvh] overflow-y-auto"
    >
      <div className="flex flex-col">
        {/* Header */}
        <div className="space-y-1 md:py-1 md:border-b border-[#F0F0F0]">
          <h2 className="text-[16px] md:text-[17.5px] md:px-5 font-display font-medium text-black/65">
            Enable Two-Factor Authentication
          </h2>
        </div>

        <div className="md:px-5 md:py-4">
          {/* Description */}
          <p className="text-[13px] md:text-[14.5px] font-display text-neutral-500">
            Add an extra layer of security to your account. Scan the QR code
            below with your authenticator app (Google Authenticator, 1Password,
            etc.).
          </p>

          {/* QR Code */}
          <div className="mx-auto bg-neutral-100 my-4 flex items-center justify-center py-1">
            <QRCode url={qrCodeUrl} scale={2} />
          </div>

          {/* Secret fallback */}
          <p className="text-[13px] md:text-[14.5px] my-2 font-display text-neutral-600">
            Can’t scan the QR code? Use this setup key instead:
          </p>

          <div className="flex items-center justify-between w-full gap-2 border border-neutral-200 bg-neutral-100/80 px-3 py-1">
            <span className="select-all font-mono text-[13px] md:text-[15px] break-all">
              {secret}
            </span>
            <CopyButton value={secret} />
          </div>

          {/* Form */}
          <form
            onSubmit={confirmTwoFactorAuth}
            className="flex w-full flex-col my-4 items-start gap-4"
          >
            <p className="text-[13px] md:text-[14.5px] font-display text-neutral-600">
              Enter the 6-digit verification code generated by your
              authenticator app.
            </p>

            <OTPInput
              maxLength={6}
              value={token}
              onChange={setToken}
              autoFocus
              render={({ slots }) => (
                <div className="flex w-full items-center justify-between gap-1">
                  {slots.map(({ char, isActive, hasFakeCaret }, idx) => (
                    <div
                      key={idx}
                      className={cn(
                        "relative flex items-center justify-center font-display",
                        "h-12 w-12 md:h-16 md:w-16 text-[20px] md:text-[24px]",
                        "border-b-[2px] border-[#E0E0E0] bg-neutral-100 transition-all",
                        isActive && "border-[#9E9E9E]",
                        ((touched && token.length < 6) || error) &&
                          "border-[#c51d1d] bg-red-50"
                      )}
                    >
                      {char}

                      {hasFakeCaret && (
                        <div className="animate-caret-blink pointer-events-none absolute inset-0 flex items-center justify-center">
                          <div className="h-5 w-px bg-black" />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            />

            {error && (
              <p className="text-[13px] md:text-sm font-display text-red-500">
                {error}
              </p>
            )}

            <Button
              className="w-full font-display h-9 md:h-10 text-sm text-white"
              text={isPending ? "Verifying..." : "Confirm"}
              type="submit"
              loading={isPending}
              disabled={token.length < 6}
            />
          </form>
        </div>
      </div>
    </Modal>
  );
};

export function useEnableTwoFactorAuthModal({
  onSuccess,
  secret,
  qrCodeUrl,
}: {
  onSuccess?: () => void;
  secret: string;
  qrCodeUrl: string;
}) {
  const [showModal, setShowModal] = useState(false);

  const ModalCallback = useCallback(
    () => (
      <EnableTwoFactorAuthModal
        showModal={showModal}
        setShowModal={setShowModal}
        onSuccess={onSuccess}
        secret={secret}
        qrCodeUrl={qrCodeUrl}
      />
    ),
    [showModal, onSuccess, secret, qrCodeUrl]
  );

  return useMemo(
    () => ({
      setShowEnableTwoFactorAuthModal: setShowModal,
      EnableTwoFactorAuthModal: ModalCallback,
    }),
    [setShowModal, ModalCallback]
  );
}
